on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: Ubuntu-latest
    env:
      POLARIS_SERVER_URL:  ${{ secrets.POLARIS_SERVER_URL }}
      POLARIS_ACCESS_TOKEN:  ${{ secrets.POLARIS_ACCESS_TOKEN }}
      BLACKDUCK_URL: ${{ secrets.BLACKDUCK_URL}}
      BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN }}
      POLARIS_FF_ENABLE_COVERITY_INCREMENTAL: true
      GH_SECRET: ${{ secrets.GH_SECRET }}
      
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    # Perform Polaris Analysis
 #   - name: polaris
  #    run: |
  #      curl -fLOsS $POLARIS_SERVER_URL/api/tools/polaris_cli-linux64.zip
  #      unzip -d /tmp -jo polaris_cli-linux64.zip
  #      /tmp/polaris -c polaris-incremental.yml analyze -w --incremental incremental-files.txt
        
    # Convert Polaris to SARIF
    - name: polaris_sarif
      run: |
        apt install nodejs
        node scripts/cov-format-sarif-for-github.js --inputFile incremental-results.json --repoName sig-demo/insecure-bank --checkoutPath sig-demo/arthur /home/ $GH_SECRET --outputFile GitHubSarif.json
        cat GitHubSarif.json
        
    # Perform Software Composition Analysis
    - name: Software Composition Analysis with Black Duck
      uses: blackducksoftware/github-action@v2
      with:
        version: 7
        args: '--blackduck.url=$BLACKDUCK_URL --blackduck.api.token=$BLACKDUCK_API_TOKEN'
