on:
  workflow_dispatch

jobs:
  build:
    runs-on: Ubuntu-latest
    env:
      BLACKDUCK_URL: ${{ secrets.BLACKDUCK_URL}}
      BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    # Perform Software Composition Analysis
    - name: Software Composition Analysis with Black Duck
      if: github.ref == 'refs/heads/teste'
      uses: blackducksoftware/github-action@v2
      with:
        version: 7
        args: '--blackduck.url=$BLACKDUCK_URL --blackduck.api.token=$BLACKDUCK_API_TOKEN'
