name: Demo - Black Duck Rapid Scan

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      BLACKDUCK_URL: ${{ secrets.BLACKDUCK_URL}}
      BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN }}
      
    steps:
      - name: check out code
        uses: actions/checkout@v2
        
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
        
    # Perform Software Composition Analysis2
      - name: Software Composition Analysis  Rapid Scan with Black Duck
        uses: blackducksoftware/github-action@v2
        with:
          version: 7
          args: '--blackduck.url="${{ secrets.BLACKDUCK_URL}}" --blackduck.api.token="${{ secrets.BLACKDUCK_API_TOKEN}}" --blackduck.trust.cert="true" --detect.blackduck.scan.mode=RAPID'
