on:
  workflow_dispatch

jobs:
  build:
    runs-on: Ubuntu-latest
    env:
      POLARIS_SERVER_URL:  ${{ secrets.POLARIS_SERVER_URL }}
      POLARIS_ACCESS_TOKEN:  ${{ secrets.POLARIS_ACCESS_TOKEN }}
      BLACKDUCK_URL: ${{ secrets.BLACKDUCK_URL}}
      BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
       
    # Perform Polaris Analysis       # echo "${{ github.GITHUB_REPOSITORY }}-server"
    - name: Polaris (SAST)
      run: |
        curl -fLOsS $POLARIS_SERVER_URL/api/tools/polaris_cli-linux64.zip
        unzip -d /tmp -jo polaris_cli-linux64.zip
        /tmp/polaris --co project.name=sig-demo/insecure-bank --co project.branch=main analyze -w

    # Perform Software Composition Analysis             
    - name: Black Duck (SCA)
      run: |
          bash <(curl -s -L https://detect.synopsys.com/detect7.sh) '--blackduck.url=$BLACKDUCK_URL \
             --blackduck.api.token=$BLACKDUCK_API_TOKEN \
             --detect.project.name=sig-demo/insecure-bank \
             --detect.project.version.name=main-HEAD \
             --detect.blackduck.signature.scanner.snippet.matching=SNIPPET_MATCHING \
             --detect.blackduck.signature.scanner.upload.source.mode=true'
